import torch
import pytest
from src.data import get_dataloaders
import os

def test_dataset_balance_and_classes():
    """
    Verify that the dataloaders strictly filter for the requested classes
    and perfectly balance the distribution of labels.
    """
    num_classes = 3  # Test specifically for classes 0, 1, 2
    batch_size = 64
    
    # We use a local ./data directory; torchvision will download it if missing
    train_loader, test_loader = get_dataloaders(data_dir="./data", batch_size=batch_size, num_classes=num_classes)
    
    for loader_name, loader in [("Train", train_loader), ("Test", test_loader)]:
        label_counts = {c: 0 for c in range(num_classes)}
        
        # Count all labels generated by the loader
        for _, labels in loader:
            for label in labels:
                lbl = label.item()
                # Assert 1: No unexpected classes exist
                if lbl >= num_classes:
                    raise ValueError(f"Found unexpected label {lbl} in {loader_name} set when num_classes={num_classes}")
                label_counts[lbl] += 1
                
        # Assert 2: The dataset is perfectly balanced
        counts = list(label_counts.values())
        if len(set(counts)) != 1:
            raise ValueError(f"{loader_name} dataset is NOT balanced. Label counts: {label_counts}")
            
        # Assert 3: Ensure the dataset isn't empty
        assert counts[0] > 0, f"{loader_name} dataset is empty."
